# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brain Teasers
email: russell.d.matt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of interesting brain teasers that I've heard over the years
baseurl: "/brain-teasers" # the subpath of your site, e.g. /blog
url: "http://russelldmatt.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
# markdown: redcarpet

highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      hidden: false
